### PR TITLE
Updated for the Swift 4.x

### PR DESCRIPTION
**Pull request by hemangshah**
I have updated the EggsBenedict code to the  Swift 3.x and also tried to convert it to Swift 4.x but there are no changes requires for the latest Swift. So I still keeping the Swift Version to 3.x. Please let me know if you need any details on this PR.

### CODE REVIEW

**Comment by hemangshah** [comment]
@jpmartha, will you check this pull-request?

**Comment by jpmartha** [comment]
@hemangshah
Oh, I'm really sorry for the late reply, and thank you for using it.🙏
I'll see your pull request later!

**Comment by jpmartha** [comment]
@hemangshah I'm really sorry.
I have a few conferences continuously. So, I'd like you to wait for a short while 🙏

**Comment by hemangshah** [comment]
@jpmartha – I can understand. But this is a very long since I make a PR. Please grab some free time and let's merge this.

**Pull request closed without merging**
